# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6cb361625e234c6fffba6520ab3a2413d9ed40e4713e31b4677f5e11a0c93f3ee26c42d9842bbfa614e26928b6e080afec610693300ad88fff5907e71f9827b9

test:
  secret_key_base: b724899834cd4f20e3375690128b04ef2f6c6ee40614c7923abfe904195c9f023a669013c6c62bb079b43c5b4814e93404f03782d49eb5bbc23a6a92b0033a2f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
